spring:
  application:
    name: pc-metrices-producer


  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

    producer:
      acks: all
      retries: 5
      linger-ms: 5
      batch-size: 16384
      buffer-memory: 33554432

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

server:
  port: 8080

metrics:
  topic: system-metrics
  publish-rate-ms: 1000

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
